name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

# 🌟 强行赋予写入权限，彻底解决 128 报错
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 升级到 v4，消除 Node.js 警告
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            
      # 升级到 v4，消除 Node.js 警告
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
